# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Config(object):
    def setupUi(self, Config):
        Config.setObjectName("Config")
        Config.resize(273, 294)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Config)
        self.verticalLayout_2.setContentsMargins(2, 6, 2, 2)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(Config)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 267, 284))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.box_tema = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.box_tema.setAlignment(QtCore.Qt.AlignCenter)
        self.box_tema.setObjectName("box_tema")
        self.grid_tema = QtWidgets.QGridLayout(self.box_tema)
        self.grid_tema.setObjectName("grid_tema")
        self.cb_tema = QtWidgets.QComboBox(self.box_tema)
        self.cb_tema.setObjectName("cb_tema")
        self.grid_tema.addWidget(self.cb_tema, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.box_tema)
        self.box_repetir = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.box_repetir.setAlignment(QtCore.Qt.AlignCenter)
        self.box_repetir.setObjectName("box_repetir")
        self.grid_repro = QtWidgets.QGridLayout(self.box_repetir)
        self.grid_repro.setObjectName("grid_repro")
        self.rd_lista = QtWidgets.QRadioButton(self.box_repetir)
        self.rd_lista.setObjectName("rd_lista")
        self.grid_repro.addWidget(self.rd_lista, 0, 0, 1, 1)
        self.rd_carpeta = QtWidgets.QRadioButton(self.box_repetir)
        self.rd_carpeta.setObjectName("rd_carpeta")
        self.grid_repro.addWidget(self.rd_carpeta, 0, 1, 1, 1)
        self.rd_video = QtWidgets.QRadioButton(self.box_repetir)
        self.rd_video.setObjectName("rd_video")
        self.grid_repro.addWidget(self.rd_video, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.box_repetir)
        self.box_avance = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.box_avance.setAlignment(QtCore.Qt.AlignCenter)
        self.box_avance.setObjectName("box_avance")
        self.gridLayout = QtWidgets.QGridLayout(self.box_avance)
        self.gridLayout.setObjectName("gridLayout")
        self.sp_avance = QtWidgets.QSpinBox(self.box_avance)
        self.sp_avance.setMinimumSize(QtCore.QSize(50, 0))
        self.sp_avance.setObjectName("sp_avance")
        self.gridLayout.addWidget(self.sp_avance, 0, 0, 1, 1)
        self.rd_min = QtWidgets.QRadioButton(self.box_avance)
        self.rd_min.setMaximumSize(QtCore.QSize(60, 16777215))
        self.rd_min.setObjectName("rd_min")
        self.gridLayout.addWidget(self.rd_min, 0, 1, 1, 1)
        self.rd_seg = QtWidgets.QRadioButton(self.box_avance)
        self.rd_seg.setMaximumSize(QtCore.QSize(70, 16777215))
        self.rd_seg.setObjectName("rd_seg")
        self.gridLayout.addWidget(self.rd_seg, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.box_avance)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)

        self.retranslateUi(Config)
        QtCore.QMetaObject.connectSlotsByName(Config)

    def retranslateUi(self, Config):
        _translate = QtCore.QCoreApplication.translate
        Config.setWindowTitle(_translate("Config", "Dialog"))
        self.box_tema.setTitle(_translate("Config", "Cambiar Tema ..."))
        self.box_repetir.setTitle(_translate("Config", "Repetir Reproducción"))
        self.rd_lista.setText(_translate("Config", "Lista"))
        self.rd_carpeta.setText(_translate("Config", "Carpeta"))
        self.rd_video.setText(_translate("Config", "Video"))
        self.box_avance.setTitle(_translate("Config", "Configurar avance de video"))
        self.rd_min.setText(_translate("Config", "Minutos"))
        self.rd_seg.setText(_translate("Config", "Segundos"))
